services:
  ldap-server:
    image: disitlab/preconf-openldap:v3 
#    image: osixia/openldap
    environment:
      LDAP_ORGANISATION: "organization"
      LDAP_DOMAIN: "ldap.organization.com"
      LDAP_ADMIN_PASSWORD: "secret"
#    command: [ "--copy-service" ] 
    ports:
      - "389:389"
      - "636:636"
    volumes:
#      - ./ldap-server-conf:/container/service/slapd/assets/config/bootstrap/ldif/custom
      - ldap-db:/var/lib/ldap
      - ldap-conf:/etc/ldap/slapd.d
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "${S4C_LOG_MAX_SIZE:-100m}"
        max-file: "${S4C_LOG_MAX_FILE:-10}"

  myldap:
    image: osixia/phpldapadmin
    environment:
      PHPLDAPADMIN_LDAP_HOSTS: "ldap-server"
    ports:
      - "6443:443"
    depends_on:
      - "ldap-server"
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "${S4C_LOG_MAX_SIZE:-100m}"
        max-file: "${S4C_LOG_MAX_FILE:-10}"
       
  postgres-db:
    image: postgres:15.7-alpine
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "keycloak"]
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: password
    volumes:
      - postgres-volume:/var/lib/postgresql/data
    logging:
      driver: "json-file"
      options:
        max-size: "${S4C_LOG_MAX_SIZE:-100m}"
        max-file: "${S4C_LOG_MAX_FILE:-10}"

  keycloak:
    image: quay.io/keycloak/keycloak:24.0.5
    restart: unless-stopped
    environment:
      KC_DB: postgres
      KC_DB_USERNAME: keycloak
      KC_DB_PASSWORD: password
      KC_DB_URL: "jdbc:postgresql://postgres-db:5432/keycloak"
      KC_METRICS_ENABLED: true
      KC_LOG_LEVEL: INFO
      KC_REALM_NAME: admin
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: secret
    ports:
      - 8088:8080
    depends_on:
      - postgres-db
      - ldap-server
    command: ["start-dev", "--http-relative-path", "/auth"]
    logging:
      driver: "json-file"
      options:
        max-size: "${S4C_LOG_MAX_SIZE:-100m}"
        max-file: "${S4C_LOG_MAX_FILE:-10}"


volumes:
  postgres-volume:
  ldap-db:
  ldap-conf:
