apiVersion: v1
kind: PersistentVolume
metadata:
  name: s4c-shared-volume
  labels:
    type: local
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: manual
  hostPath:
    path: /local-volume-path/shared-volume
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: s4c-pvc-shared-volume
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: manual
  resources:
    requests:
      storage: 5Gi
---
apiVersion: v1
kind: Pod
metadata:
  name: s4c-shared-volume-app
spec:
  containers:
    - name: app
      image: disitlab/s4c-setup-tools
      command: ["/bin/sh"]
      args: ["-c", "while true; do echo $(date -u) >> /data/out.log; sleep 10m; done"]
      volumeMounts:
        - name: persistent-storage
          mountPath: /data
  volumes:
    - name: persistent-storage
      persistentVolumeClaim:
        claimName: s4c-pvc-shared-volume

