version: "3.2"
services:
  opensearch-n1:
    container_name: opensearch-n1
    image: opensearchproject/opensearch:1.2.3
    environment:
      - discovery.type=multi-node
      - cluster.name=snap4city-opensearch-cluster
      - node.name=opensearch-n1
      - discovery.seed_hosts=$#seed_hosts#$
      - DISABLE_INSTALL_DEMO_CONFIG=true
      - network.host=0.0.0.0
      - network.publish_host=$#id_ip#$
      - JAVA_HOME=/usr/share/opensearch/jdk
    hostname: opensearch-n1
    ports:
      - "9200:9200"
      - "9300:9300"
    extra_hosts:
$#hosts_less#$
    volumes:
      - opensearch-data:/usr/share/opensearch/data
      - ./opensearch-conf/root-ca.pem:/usr/share/opensearch/config/root-ca.pem
      - ./opensearch-conf/node.pem:/usr/share/opensearch/config/esnode.pem
      - ./opensearch-conf/node-key.pem:/usr/share/opensearch/config/esnode-key.pem
      - ./opensearch-conf/admin.pem:/usr/share/opensearch/config/admin.pem
      - ./opensearch-conf/admin-key.pem:/usr/share/opensearch/config/admin-key.pem
      - ./opensearch-conf/opensearch.yml:/usr/share/opensearch/config/opensearch.yml
      - ./opensearch-conf/security-config.yml:/usr/share/opensearch/plugins/opensearch-security/securityconfig/config.yml
      - ./opensearch-conf/internal_users.yml:/usr/share/opensearch/plugins/opensearch-security/securityconfig/internal_users.yml
      - ./opensearch-conf/roles_mapping.yml:/usr/share/opensearch/plugins/opensearch-security/securityconfig/roles_mapping.yml
      - ./opensearch-conf/tenants.yml:/usr/share/opensearch/plugins/opensearch-security/securityconfig/tenants.yml
      - ./opensearch-conf/roles.yml:/usr/share/opensearch/plugins/opensearch-security/securityconfig/roles.yml
      - ./opensearch-conf/action_groups.yml:/usr/share/opensearch/plugins/opensearch-security/securityconfig/action_groups.yml
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "${S4C_LOG_MAX_SIZE:-100m}"
        max-file: "${S4C_LOG_MAX_FILE:-10}"
  opensearch-dashboards:
    image: opensearchproject/opensearch-dashboards:1.2.0
    container_name: opensearch-dashboards
    ports:
      - 5601:5601
    environment:
      OPENSEARCH_HOSTS: '["https://opensearch-n1:9200"]' # must be a string with no spaces when specified as an environment variable
      SERVER_BASEPATH: '/kibana'
      SERVER_REWRITEBASEPATH: 'false'
      OPENSEARCH_USER: kibanaserver
      OPENSEARCH_PASSWORD: $#opensearch-admin-pwd#$
    depends_on:
      - opensearch-n1
    volumes:
      - ./opensearch-conf/opensearch_dashboards.yml:/usr/share/opensearch-dashboards/config/opensearch_dashboards.yml
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "${S4C_LOG_MAX_SIZE:-100m}"
        max-file: "${S4C_LOG_MAX_FILE:-10}"

volumes:
  elastic-data:
  opensearch-data:
