version: "3.2"
services:
  ldap-server:
    container_name: ldap-server
    restart: unless-stopped
    #image: osixia/openldap:latest
    image: disitlab/preconf-openldap:v3
    command: ["bash", "/ldif_files/run.sh"]
    volumes:
      - ./ldap/:/ldif_files
      - ldap_lib:/var/lib/ldap
      - ldap_etc:/etc/ldap/slapd.d
    environment:
      LDAP_ORGANISATION: "$#ldap-organization#$"
      LDAP_DOMAIN: "ldap.$#ldap-organization#$.com"
      LDAP_ADMIN_PASSWORD: "$#ldap-admin-pwd#$"
    ports:
      - "389:389"
      - "636:636"

    logging:
      driver: "json-file"
      options:
        max-size: "${S4C_LOG_MAX_SIZE:-100m}"
        max-file: "${S4C_LOG_MAX_FILE:-10}"
  myldap:
    container_name: myldap
    restart: unless-stopped
    image: osixia/phpldapadmin
    environment:
      PHPLDAPADMIN_LDAP_HOSTS: "ldap-server"
    ports:
      - "6443:443"
    depends_on:
      - "ldap-server"

    logging:
      driver: "json-file"
      options:
        max-size: "${S4C_LOG_MAX_SIZE:-100m}"
        max-file: "${S4C_LOG_MAX_FILE:-10}"


  postgres-db:
    image: postgres:15.7-alpine
    restart: unless-stopped
    container_name: postgres-db
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "keycloak"]
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: $#dashboard-db-pwd#$
    volumes:
      - postgres-volume:/var/lib/postgresql/data
    logging:
      driver: "json-file"
      options:
        max-size: "${S4C_LOG_MAX_SIZE:-100m}"
        max-file: "${S4C_LOG_MAX_FILE:-10}"

  keycloak:
    image: quay.io/keycloak/keycloak:24.0.5
    restart: unless-stopped
    container_name: keycloak
    environment:
      KC_PROXY_ADDRESS_FORWARDING: "true"
      KC_DB: postgres
      KC_DB_USERNAME: keycloak
      KC_DB_PASSWORD: $#dashboard-db-pwd#$
      KC_DB_URL: "jdbc:postgresql://postgres-db:5432/keycloak"
      KC_METRICS_ENABLED: "true"
      KC_PROXY: edge
      KC_LOG_LEVEL: INFO
      KC_REALM_NAME: admin
      KEYCLOAK_ADMIN: $#keycloak-admin#$
      KEYCLOAK_ADMIN_PASSWORD: $#keycloak-admin-pwd#$
      KC_HOSTNAME_STRICT: "false"
      KC_HTTP_RELATIVE_PATH: "/auth"
    ports:
      - 8088:8080
    depends_on:
      - postgres-db
      - ldap-server
    command: ["start"]
    logging:
      driver: "json-file"
      options:
        max-size: "${S4C_LOG_MAX_SIZE:-100m}"
        max-file: "${S4C_LOG_MAX_FILE:-10}"    

volumes:
  ldap_etc: {}
  ldap_lib: {}
  keycloak: {}
  postgres-volume: {}
