apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    io.kompose.service: $#pvc-name#$
  name: $#pvc-name#$
spec:
  volumeName: $#pvc-name#$
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 100Mi
  storageClassName: manual