apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    io.kompose.service: $#pvc-name#$
  name: $#pvc-name#$
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
  storageClassName: efs-sc