apiVersion: v1
kind: PersistentVolume
metadata:
  name: $#volume-name#$
  labels:
    type: local
spec:
  capacity:
    storage: 100Mi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Recycle
  storageClassName: manual
  hostPath:
    path: "$#volume-path#$"
